// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// EventListResponse defines model for EventListResponse.
type EventListResponse struct {
	Items []StoredEvent `json:"items"`
	Total int64         `json:"total"`
}

// StoredEvent defines model for StoredEvent.
type StoredEvent struct {
	ChangeTag     string     `json:"change_tag"`
	CreatedAt     *time.Time `json:"created_at,omitempty"`
	EventTime     time.Time  `json:"event_time"`
	Id            string     `json:"id"`
	Initiator     string     `json:"initiator"`
	PublishedTime time.Time  `json:"published_time"`
	SourceSystem  string     `json:"source_system"`
	StateAfter    *string    `json:"state_after"`
	StateBefore   *string    `json:"state_before"`
}

// ListEventsParams defines parameters for ListEvents.
type ListEventsParams struct {
	SourceSystem *string    `form:"source_system,omitempty" json:"source_system,omitempty"`
	ChangeTag    *string    `form:"change_tag,omitempty" json:"change_tag,omitempty"`
	Search       *string    `form:"search,omitempty" json:"search,omitempty"`
	From         *time.Time `form:"from,omitempty" json:"from,omitempty"`
	To           *time.Time `form:"to,omitempty" json:"to,omitempty"`
	Limit        *int       `form:"limit,omitempty" json:"limit,omitempty"`
	Offset       *int       `form:"offset,omitempty" json:"offset,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /events)
	ListEvents(ctx echo.Context, params ListEventsParams) error

	// (GET /events/{id})
	GetEventById(ctx echo.Context, id string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListEvents converts echo context to params.
func (w *ServerInterfaceWrapper) ListEvents(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListEventsParams
	// ------------- Optional query parameter "source_system" -------------

	err = runtime.BindQueryParameter("form", true, false, "source_system", ctx.QueryParams(), &params.SourceSystem)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_system: %s", err))
	}

	// ------------- Optional query parameter "change_tag" -------------

	err = runtime.BindQueryParameter("form", true, false, "change_tag", ctx.QueryParams(), &params.ChangeTag)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter change_tag: %s", err))
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameter("form", true, false, "search", ctx.QueryParams(), &params.Search)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter search: %s", err))
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameter("form", true, false, "from", ctx.QueryParams(), &params.From)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter from: %s", err))
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameter("form", true, false, "to", ctx.QueryParams(), &params.To)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter to: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListEvents(ctx, params)
	return err
}

// GetEventById converts echo context to params.
func (w *ServerInterfaceWrapper) GetEventById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetEventById(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/events", wrapper.ListEvents)
	router.GET(baseURL+"/events/:id", wrapper.GetEventById)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7SVTWvbTBDHv0qY5zmqltKUHnRrIZTQQkpzDMGMtSN7UmlXmR0FhNF3L7tyEsuSShra",
	"22o985+X/c14D4WrG2fJqod8D77YUY3xePlIVr+x1x/kG2c9hctGXEOiTNGElerx4X+hEnL4L32RTQ+a",
	"6Y06IRNloU9Au4YgBxTBLn47xSpolE5qVMiBrX78AM+WbJW2JND3CQg9tCxkIL89BH8SuHu2d5t7KmKo",
	"48iTIood2i2tFbfh6+DrVdhug28hhEpmjTrKzaDSO+WaICSD5tpWHeQqLSVTDQqR19F6SWPiw2Y2Hbas",
	"jOpk9tem3VTsd2T+MJh3rRS09p1XqmeVvaLSGkulGNm2VYWbihZLHuw3VDqhVzicPqmB06RGXZxUetyY",
	"5PhJpzj0sYuli2WyhpQG1s9u2P48+/T9ChJ4JPHsLORwvspWWajINWSxYcjhYpWtLkIOqLuIUBpTi8ct",
	"RU4CYKjs7JWBHMIUXQ4mwUuwJiXxkN/ugUOQh5akgwQs1rErJ5UPEzTzLn0yL3DUgDd4e0Ipdm/xLMWN",
	"830Nfkti6v6aVMU160jNUIltpZCfZ9nchpnXcWXpaUFoTuYuYD1sz0jH+yyLK8dZPewibJqKi4hKeu8D",
	"cfsj8d+t0+l+jmgb8oVwowO911/DbZ88IZru2fSLnH6hAdPP3ZVZIDUw/9KPOKcvgzuM9jI1/7Ido3+X",
	"xUb0/a8AAAD//xTvU+3yBgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
