// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// EventListResponse defines model for EventListResponse.
type EventListResponse struct {
	Items      []StoredEvent `json:"items"`
	Page       int           `json:"page"`
	PageSize   int           `json:"page_size"`
	Total      int64         `json:"total"`
	TotalPages int           `json:"total_pages"`
}

// StoredEvent defines model for StoredEvent.
type StoredEvent struct {
	CreatedAt   *time.Time `json:"created_at,omitempty"`
	Description *string    `json:"description"`
	EventTime   time.Time  `json:"event_time"`
	EventType   string     `json:"event_type"`
	Id          string     `json:"id"`
	Initiator   string     `json:"initiator"`

	// InitiatorName Читаемое имя инициатора (опционально)
	InitiatorName *string   `json:"initiator_name"`
	PublishedTime time.Time `json:"published_time"`
	SourceSystem  string    `json:"source_system"`
	StateAfter    *string   `json:"state_after"`
	StateBefore   *string   `json:"state_before"`
	Status        *string   `json:"status"`
	Tag           string    `json:"tag"`

	// TraceId Опциональный идентификатор трассировки
	TraceId *string `json:"trace_id"`
}

// ListEventsParams defines parameters for ListEvents.
type ListEventsParams struct {
	SourceSystem *string `form:"source_system,omitempty" json:"source_system,omitempty"`
	EventType    *string `form:"event_type,omitempty" json:"event_type,omitempty"`
	Status       *string `form:"status,omitempty" json:"status,omitempty"`

	// Search Поиск по initiator и description
	Search   *string    `form:"search,omitempty" json:"search,omitempty"`
	Tag      *string    `form:"tag,omitempty" json:"tag,omitempty"`
	From     *time.Time `form:"from,omitempty" json:"from,omitempty"`
	To       *time.Time `form:"to,omitempty" json:"to,omitempty"`
	Page     *int       `form:"page,omitempty" json:"page,omitempty"`
	PageSize *int       `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /events)
	ListEvents(ctx echo.Context, params ListEventsParams) error

	// (GET /events/{id})
	GetEventById(ctx echo.Context, id string) error

	// (GET /health)
	Health(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListEvents converts echo context to params.
func (w *ServerInterfaceWrapper) ListEvents(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListEventsParams
	// ------------- Optional query parameter "source_system" -------------

	err = runtime.BindQueryParameter("form", true, false, "source_system", ctx.QueryParams(), &params.SourceSystem)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_system: %s", err))
	}

	// ------------- Optional query parameter "event_type" -------------

	err = runtime.BindQueryParameter("form", true, false, "event_type", ctx.QueryParams(), &params.EventType)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter event_type: %s", err))
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", ctx.QueryParams(), &params.Status)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter status: %s", err))
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameter("form", true, false, "search", ctx.QueryParams(), &params.Search)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter search: %s", err))
	}

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameter("form", true, false, "tag", ctx.QueryParams(), &params.Tag)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tag: %s", err))
	}

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameter("form", true, false, "from", ctx.QueryParams(), &params.From)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter from: %s", err))
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameter("form", true, false, "to", ctx.QueryParams(), &params.To)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter to: %s", err))
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", ctx.QueryParams(), &params.PageSize)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page_size: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListEvents(ctx, params)
	return err
}

// GetEventById converts echo context to params.
func (w *ServerInterfaceWrapper) GetEventById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetEventById(ctx, id)
	return err
}

// Health converts echo context to params.
func (w *ServerInterfaceWrapper) Health(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Health(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/events", wrapper.ListEvents)
	router.GET(baseURL+"/events/:id", wrapper.GetEventById)
	router.GET(baseURL+"/health", wrapper.Health)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RWT6/bRBD/KtbCASTz4raIg28gVfAEUhE9VpW1sSfJFtvr7o4rQmSpL0JcQOIbwJFr",
	"hHiSeTTuVxh/I7Rr5yWO7Zf0Aac4O7O/mfnNv12xUCaZTCFFzfwV0+ECEm4/H7+CFL8SGr8BnclUgznM",
	"lMxAoQCrIhCS7sf7CmbMZ+9N9rCTFnPyFKWCyMKywmW4zID5jCvFl+Z/xufWRHsuUoQ5qJ0k0OL7ETFK",
	"5LERzaRKODbCTz5m7phuYAD1EFjhMgUvc6EgYv6zNqydhdbFQ3+6gM9vLcrpCwhtlIdB9/gLFXCEKODY",
	"cT/iCB+hSAy+Ah49SeMl81HlcGtAoxLp3BiIQIdKZChkakDSPI75NIZRfTCuBBZ9zObYHXu86otFNHyc",
	"ChQcpbpbGqS88aUTCaPfqazXtKFrekMVXTtU0pv6F/OzpbL+kUra1Guq6te0cT6git7as4q2tKG/659p",
	"S9WHzD1NSJZPY6EXEL0jKVrmKoRALzVCMhiiRo4Q8BmCOis1jf4UZlLB2RdyfZYq8vmgj6h4CEGTwaME",
	"/NqntP6J/jIZ+JOuaVuvqax/oJJudplw6rVJR31VX1FZv6aK/qAbKk9n4bjvInbMb6dwe0k7LLYm1k7R",
	"9huzsBU4k5YTgcaxZuA5T0X6rfPp15fMZa9A6YaLBxfehWfokhmkPBPMZ48uvItHdhjgwqZgYg3azznY",
	"hjatzg2blxHzmRmljxsVc0vxBBCUZv6zFRPGyMsc1NJwZfuhF38zRgeSWLjDAAcE3ON2W1snbh6VzG9U",
	"UVlf0Y1Db6lybpPiUOkcqrrDJoGrcHEfZ5uMv/O1mZJdZs/p/FEf5H8G1e6ZPVgEM57HyPwHLktEKpI8",
	"sd/9/TUOuNtYA6gPPZcl/LsW1vNOGHluurV5E9hyf+h5dpvJFNs1x7MsFqGt/ckL3Wymvd27Hgn9V4ft",
	"1W6dPfnSnBburucmKxEVo433OTR999nyMhppPdPEe7bs+NnPo2ZijRfX/0lH5810FxEL4DEuRjn4ohH/",
	"S0+7r5f99ulP84FxO+h5UfwTAAD//1+v80aCCgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
